spring:
  application:
    name: auth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST}