spring:
  application:
    name: healthy-eating-tip

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  datasource:
    url: jdbc:postgresql://localhost:5432/as_healthy_eating_tip
    username: postgres
    password: 123456

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka