spring:
  application:
    name: membership

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  datasource:
    url: jdbc:postgresql://localhost:5432/as_membership
    username: postgres
    password: 123456

server:
  port: 8084

userProfileClientUrl: http://localhost:8081
organizationClientUrl: http://localhost:8086

