spring:
  application:
    name: user-profile

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  datasource:
    url: jdbc:postgresql://localhost:5432/as_user_profile
    username: postgres
    password: 123456

server:
  port: 8088
