spring:
  application:
    name: training

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  datasource:
    url: jdbc:postgresql://localhost:5432/as_training
    username: postgres
    password: 123456

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8087

userProfileClientUrl: http://localhost:8081
organizationClientUrl: http://localhost:8086
