spring:
  application:
    name: organization

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validations:
            mode: none

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/as_organization
    username: postgres
    password: 123456

server:
  port: 8087

userProfileClientUrl: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka